name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 16.171.71.49
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
              cd ~/100devs-ci-cd

              echo "ğŸ§¹ Pulling latest code..."
              git pull origin main

              echo "ğŸ“¦ Installing dependencies..."
              npm install --force

              echo "ğŸ—ï¸ Building project..."
              npm run build

              echo "ğŸš€ Restarting app with PM2..."
              pm2 delete all || true
              pm2 start 'npm run start -- -H 0.0.0.0' --name app
              pm2 save

              echo "âœ… Deployment completed successfully!"
            

